import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { useToast } from "@/hooks/use-toast";
import { ButtonLoader } from "@/components/ui/loader";
import { queryClient } from "@/lib/queryClient";
import { insertLeadSchema, type Lead, type InsertLead } from "../../shared/schema";
import { leadsService } from "@/lib/apis";
import type { CreateLeadDto, UpdateLeadDto, LeadResponse } from "@/lib/apis";
import { CustomerCategory, LeadStatus, LeadSource } from "@/lib/apis";
import { User, MapPin, Building, MessageSquare, X } from "lucide-react";
import { useState } from "react";

interface LeadFormProps {
  lead?: Lead | null;
  onClose: () => void;
}

export default function LeadForm({ lead, onClose }: LeadFormProps) {
  const { toast } = useToast();
  const isEditing = Boolean(lead);
  const [lastContactedByCount, setLastContactedByCount] = useState(lead?.lastContactedBy?.length || 0);
  const [interestedInCount, setInterestedInCount] = useState(lead?.customerInterestedIn?.length || 0);
  const [notesCount, setNotesCount] = useState(lead?.additionalNotes?.length || 0);
  const [customSourceCount, setCustomSourceCount] = useState(lead?.customLeadSource?.length || 0);
  const [customReferralCount, setCustomReferralCount] = useState(lead?.customReferralSource?.length || 0);
  const [customGeneratedByCount, setCustomGeneratedByCount] = useState(lead?.customGeneratedBy?.length || 0);
  const [customCommChannelCount, setCustomCommChannelCount] = useState(lead?.customCommunicationChannel?.length || 0);
  const [leadCreatedByCount, setLeadCreatedByCount] = useState(lead?.leadCreatedBy?.length || 0);

  // Helper functions to format enum labels
  const formatLeadStatusLabel = (status: LeadStatus): string => {
    const labels: Record<LeadStatus, string> = {
      [LeadStatus.NEW]: "New Lead",
      [LeadStatus.FOLLOWUP]: "Follow-up",
      [LeadStatus.QUALIFIED]: "Qualified",
      [LeadStatus.HOT]: "Hot Lead",
      [LeadStatus.CONVERTED]: "Converted to Customer",
      [LeadStatus.LOST]: "Lost",
    };
    return labels[status] || status;
  };

  const formatLeadSourceLabel = (source: LeadSource): string => {
    const labels: Record<LeadSource, string> = {
      [LeadSource.WEBSITE]: "Website/Internet",
      [LeadSource.REFERRAL]: "Referral",
      [LeadSource.LINKEDIN]: "LinkedIn",
      [LeadSource.FACEBOOK]: "Facebook",
      [LeadSource.TWITTER]: "Twitter",
      [LeadSource.INSTAGRAM]: "Instagram",
      [LeadSource.CAMPAIGN]: "Campaign/Roadshow",
      [LeadSource.GENERATED_BY]: "Generated By",
      [LeadSource.ON_FIELD]: "On Field",
      [LeadSource.OTHER]: "Other",
    };
    return labels[source] || source;
  };

  const formatCustomerCategoryLabel = (category: CustomerCategory): string => {
    return category === CustomerCategory.EXISTING ? "Existing Customer" : "Potential Customer";
  };

  const form = useForm<InsertLead>({
    resolver: zodResolver(insertLeadSchema),
    defaultValues: {
      name: lead?.name || "",
      phoneNumber: lead?.phoneNumber || "",
      email: lead?.email || "",
      dateOfBirth: lead?.dateOfBirth || "",
      city: lead?.city || "",
      state: lead?.state || "",
      country: lead?.country || "",
      pincode: lead?.pincode || "",
      companyName: lead?.companyName || "",
      designation: lead?.designation || "",
      customerCategory: (lead?.customerCategory as CustomerCategory) || CustomerCategory.POTENTIAL,
      lastContactedDate: lead?.lastContactedDate || "",
      lastContactedBy: lead?.lastContactedBy || "",
      nextFollowupDate: lead?.nextFollowupDate || "",
      customerInterestedIn: lead?.customerInterestedIn || "",
      preferredCommunicationChannel: (lead?.preferredCommunicationChannel as "email" | "phone" | "whatsapp" | "sms" | "in-person" | "linkedin" | "other") || undefined,
      customCommunicationChannel: lead?.customCommunicationChannel || "",
      leadSource: (lead?.leadSource as LeadSource) || undefined,
      customLeadSource: lead?.customLeadSource || "",
      customReferralSource: lead?.customReferralSource || "",
      customGeneratedBy: lead?.customGeneratedBy || "",
      leadStatus: (lead?.leadStatus as LeadStatus) || LeadStatus.NEW,
      leadCreatedBy: lead?.leadCreatedBy || "",
      additionalNotes: lead?.additionalNotes || "",
    },
  });

  // Convert InsertLead to CreateLeadDto
  const convertToCreateDto = (data: InsertLead): CreateLeadDto => {
    return {
      name: data.name,
      phoneNumber: data.phoneNumber,
      email: data.email || undefined,
      dateOfBirth: data.dateOfBirth ? data.dateOfBirth : undefined,
      city: data.city || undefined,
      state: data.state || undefined,
      country: data.country || undefined,
      pincode: data.pincode || undefined,
      companyName: data.companyName || undefined,
      designation: data.designation || undefined,
      customerCategory: data.customerCategory as CustomerCategory,
      lastContactedDate: data.lastContactedDate ? data.lastContactedDate : undefined,
      lastContactedBy: data.lastContactedBy || undefined,
      nextFollowupDate: data.nextFollowupDate ? data.nextFollowupDate : undefined,
      customerInterestedIn: data.customerInterestedIn || undefined,
      preferredCommunicationChannel: data.preferredCommunicationChannel || undefined,
      customCommunicationChannel: data.customCommunicationChannel || undefined,
      leadSource: data.leadSource as LeadSource,
      customLeadSource: data.customLeadSource || undefined,
      customReferralSource: data.customReferralSource || undefined,
      customGeneratedBy: data.customGeneratedBy || undefined,
      leadStatus: (data.leadStatus as LeadStatus) || LeadStatus.NEW,
      leadCreatedBy: data.leadCreatedBy || undefined,
      additionalNotes: data.additionalNotes || undefined,
    };
  };

  // Convert InsertLead to UpdateLeadDto
  const convertToUpdateDto = (data: InsertLead): UpdateLeadDto => {
    return {
      name: data.name,
      phoneNumber: data.phoneNumber,
      email: data.email || undefined,
      dateOfBirth: data.dateOfBirth ? data.dateOfBirth : undefined,
      city: data.city || undefined,
      state: data.state || undefined,
      country: data.country || undefined,
      pincode: data.pincode || undefined,
      companyName: data.companyName || undefined,
      designation: data.designation || undefined,
      customerCategory: data.customerCategory as CustomerCategory,
      lastContactedDate: data.lastContactedDate ? data.lastContactedDate : undefined,
      lastContactedBy: data.lastContactedBy || undefined,
      nextFollowupDate: data.nextFollowupDate ? data.nextFollowupDate : undefined,
      customerInterestedIn: data.customerInterestedIn || undefined,
      preferredCommunicationChannel: data.preferredCommunicationChannel || undefined,
      customCommunicationChannel: data.customCommunicationChannel || undefined,
      leadSource: data.leadSource as LeadSource,
      customLeadSource: data.customLeadSource || undefined,
      customReferralSource: data.customReferralSource || undefined,
      customGeneratedBy: data.customGeneratedBy || undefined,
      leadStatus: (data.leadStatus as LeadStatus) || LeadStatus.NEW,
      leadCreatedBy: data.leadCreatedBy || undefined,
      additionalNotes: data.additionalNotes || undefined,
    };
  };

  const createMutation = useMutation({
    mutationFn: async (data: InsertLead) => {
      const createDto = convertToCreateDto(data);
      return await leadsService.createLead(createDto);
    },
    onSuccess: () => {
      // Invalidate queries to refresh data
      queryClient.invalidateQueries({ queryKey: ["/api/leads"] });
      queryClient.invalidateQueries({ queryKey: ["/api/analytics"] });
      
      toast({
        title: "Lead Added Successfully",
        description: "The new lead has been saved.",
      });
      onClose();
    },
    onError: (error: any) => {
      let errorMessage = "We couldn't save this lead. Please check your information and try again.";
      
      // Extract user-friendly message from error response
      if (error?.message) {
        // Remove HTTP status codes and technical details
        let message = error.message.replace(/^\d+:\s*/, ''); // Remove status codes like "400: "
        
        // Remove JSON formatting if present
        if (message.includes('{"error":') || message.includes('{"message":')) {
          try {
            const parsed = JSON.parse(message);
            message = parsed.error || parsed.message || message;
          } catch {
            // If JSON parsing fails, use the original message
          }
        }
        
        if (!message.includes('Failed to fetch') && !message.includes('NetworkError')) {
          errorMessage = message;
        }
      }
      
      toast({
        title: "Unable to Save Lead",
        description: errorMessage,
        variant: "destructive",
      });
    },
  });

  const updateMutation = useMutation({
    mutationFn: async (data: InsertLead) => {
      if (!lead?.id) {
        throw new Error("Lead ID is required for update");
      }
      const updateDto = convertToUpdateDto(data);
      return await leadsService.updateLead(lead.id, updateDto);
    },
    onSuccess: () => {
      // Invalidate queries to refresh data
      queryClient.invalidateQueries({ queryKey: ["/api/leads"] });
      queryClient.invalidateQueries({ queryKey: ["/api/analytics"] });
      
      toast({
        title: "Lead Updated Successfully",
        description: "The lead information has been updated.",
      });
      onClose();
    },
    onError: (error: any) => {
      let errorMessage = "We couldn't update this lead. Please check your information and try again.";
      
      // Extract user-friendly message from error response
      if (error?.message) {
        // Remove HTTP status codes and technical details
        let message = error.message.replace(/^\d+:\s*/, ''); // Remove status codes like "400: "
        
        // Remove JSON formatting if present
        if (message.includes('{"error":') || message.includes('{"message":')) {
          try {
            const parsed = JSON.parse(message);
            message = parsed.error || parsed.message || message;
          } catch {
            // If JSON parsing fails, use the original message
          }
        }
        
        if (!message.includes('Failed to fetch') && !message.includes('NetworkError')) {
          errorMessage = message;
        }
      }
      
      toast({
        title: "Unable to Update Lead",
        description: errorMessage,
        variant: "destructive",
      });
    },
  });

  const onSubmit = (data: InsertLead) => {
    if (lead) {
      updateMutation.mutate(data);
    } else {
      createMutation.mutate(data);
    }
  };

  const isPending = createMutation.isPending || updateMutation.isPending;

  return (
    <>
      <DialogHeader className="flex flex-row items-center justify-between">
        <DialogTitle data-testid="form-title">{lead ? "Edit Lead" : "Add New Lead"}</DialogTitle>
        <div className="flex space-x-2 mr-8">
          <Button type="button" variant="outline" onClick={onClose} data-testid="button-cancel" size="sm">
            Cancel
          </Button>
          <Button type="submit" form="lead-form" disabled={isPending} data-testid="button-save" size="sm">
            {isPending ? (
              <div className="flex items-center">
                <ButtonLoader size={14} color="#ffffff" />
                <span className="ml-2">Saving...</span>
              </div>
            ) : (
              lead ? "Update Lead" : "Save Lead"
            )}
          </Button>
        </div>
      </DialogHeader>

      <Form {...form}>
        <form id="lead-form" onSubmit={form.handleSubmit(onSubmit)} className="space-y-3">
          {isEditing ? (
            <>
              {/* Top Section for Edit Lead: Next Followup Date, Lead Status, Additional Notes */}
              <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                <FormField
                  control={form.control}
                  name="nextFollowupDate"
                  render={({ field }) => {
                    // Helper function to update lastContactedDate to today
                    const updateLastContactedDate = () => {
                      const today = new Date();
                      const isoToday = new Date(today.getTime() - today.getTimezoneOffset() * 60000)
                        .toISOString()
                        .split("T")[0];
                      form.setValue("lastContactedDate", isoToday, { shouldDirty: true });
                    };

                    return (
                      <FormItem>
                        <FormLabel className="text-xs">Next Followup Date</FormLabel>
                        <FormControl>
                          <div className="relative">
                            <Input
                              type="date"
                              {...field}
                              value={field.value || ""}
                              onChange={(e) => {
                                const value = e.target.value;
                                field.onChange(value || null);
                                // Always update lastContactedDate when nextFollowupDate changes or is cleared
                                updateLastContactedDate();
                              }}
                              data-testid="input-next-followup-date"
                            />
                            {field.value && (
                              <button
                                type="button"
                                onClick={() => {
                                  field.onChange(null);
                                  // Update lastContactedDate when clearing the field
                                  updateLastContactedDate();
                                }}
                                className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                                title="Clear date"
                              >
                                <X className="h-4 w-4" />
                              </button>
                            )}
                          </div>
                        </FormControl>
                        <FormMessage />
                        <p className="text-xs text-gray-500">Must be today or in the future</p>
                      </FormItem>
                    );
                  }}
                />

                <FormField
                  control={form.control}
                  name="leadStatus"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">
                        Lead Status <span className="text-red-500">*</span>
                      </FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-lead-status">
                            <SelectValue placeholder="Select status" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {Object.values(LeadStatus).map((status) => (
                            <SelectItem key={status} value={status}>
                              {formatLeadStatusLabel(status)}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="additionalNotes"
                  render={({ field }) => (
                    <FormItem className="md:col-span-2">
                      <FormLabel className="text-xs">Additional Notes</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Add any additional notes (max 200 characters)"
                          maxLength={200}
                          rows={1}
                          className="min-h-[32px] resize-none"
                          {...field}
                          onChange={(e) => {
                            field.onChange(e);
                            setNotesCount(e.target.value.length);
                          }}
                          data-testid="textarea-additional-notes"
                        />
                      </FormControl>
                      <p className="text-xs text-gray-500 mt-0.5" data-testid="text-notes-count">
                        {notesCount}/200 characters
                      </p>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <Separator className="my-2" />

              {/* Priority Order Fields (4-20) */}
              <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                {/* Priority 4: Company Name */}
                <FormField
                  control={form.control}
                  name="companyName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Company Name</FormLabel>
                      <FormControl>
                        <Input placeholder="Enter company name" {...field} data-testid="input-company" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 5: Contact Person (Full Name) */}
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">
                        Full Name <span className="text-red-500">*</span>
                      </FormLabel>
                      <FormControl>
                        <Input placeholder="Enter full name" {...field} data-testid="input-name" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 6: Designation */}
                <FormField
                  control={form.control}
                  name="designation"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Designation</FormLabel>
                      <FormControl>
                        <Input placeholder="Enter designation" {...field} data-testid="input-designation" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 7: Phone Number */}
                <FormField
                  control={form.control}
                  name="phoneNumber"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">
                        Phone Number <span className="text-red-500">*</span>
                      </FormLabel>
                      <FormControl>
                        <Input placeholder="Enter phone number" {...field} data-testid="input-phone" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 8: Email Address */}
                <FormField
                  control={form.control}
                  name="email"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Email Address</FormLabel>
                      <FormControl>
                        <Input type="email" placeholder="john@example.com" {...field} data-testid="input-email" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 9: Preferred Communication Channel */}
                <FormField
                  control={form.control}
                  name="preferredCommunicationChannel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Preferred Communication Channel</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-communication-channel">
                            <SelectValue placeholder="Select channel" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="email">Email</SelectItem>
                          <SelectItem value="phone">Phone</SelectItem>
                          <SelectItem value="whatsapp">WhatsApp</SelectItem>
                          <SelectItem value="sms">SMS</SelectItem>
                          <SelectItem value="in-person">In Person</SelectItem>
                          <SelectItem value="linkedin">LinkedIn</SelectItem>
                          <SelectItem value="other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 10: Customer Interested In */}
                <FormField
                  control={form.control}
                  name="customerInterestedIn"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Customer Interested in</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="Describe customer interests (max 100 characters)"
                          maxLength={100}
                          {...field}
                          onChange={(e) => {
                            field.onChange(e);
                            setInterestedInCount(e.target.value.length);
                          }}
                          data-testid="input-customer-interested-in"
                        />
                      </FormControl>
                      <p className="text-xs text-gray-500 mt-0.5" data-testid="text-interested-in-count">
                        {interestedInCount}/100 characters
                      </p>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 11: City */}
                <FormField
                  control={form.control}
                  name="city"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">City</FormLabel>
                      <FormControl>
                        <Input placeholder="Enter city" {...field} data-testid="input-city" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 12: State */}
                <FormField
                  control={form.control}
                  name="state"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">State</FormLabel>
                      <FormControl>
                        <Input placeholder="Enter state" {...field} data-testid="input-state" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 13: Country */}
                <FormField
                  control={form.control}
                  name="country"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Country</FormLabel>
                      <FormControl>
                        <Input placeholder="Enter country" {...field} data-testid="input-country" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 14: Pincode/Zipcode */}
                <FormField
                  control={form.control}
                  name="pincode"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Pincode/Zipcode</FormLabel>
                      <FormControl>
                        <Input placeholder="123456" {...field} data-testid="input-pincode" />
                      </FormControl>
                      <FormMessage />
                      <p className="text-xs text-gray-500">6 digits for Indian pincodes</p>
                    </FormItem>
                  )}
                />

                {/* Priority 15: Lead Source */}
                <FormField
                  control={form.control}
                  name="leadSource"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">
                        Lead Source <span className="text-red-500">*</span>
                      </FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-lead-source">
                            <SelectValue placeholder="Select lead source" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {Object.values(LeadSource).map((source) => (
                            <SelectItem key={source} value={source}>
                              {formatLeadSourceLabel(source)}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 16: Last Contacted Date */}
                <FormField
                  control={form.control}
                  name="lastContactedDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Last Contacted Date</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <Input 
                            type="date" 
                            {...field} 
                            value={field.value || ""}
                            onChange={(e) => field.onChange(e.target.value || null)}
                            data-testid="input-last-contacted-date" 
                          />
                          {field.value && (
                            <button
                              type="button"
                              onClick={() => field.onChange(null)}
                              className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                              title="Clear date"
                            >
                              <X className="h-4 w-4" />
                            </button>
                          )}
                        </div>
                      </FormControl>
                      <FormMessage />
                      <p className="text-xs text-gray-500">Cannot be in the future</p>
                    </FormItem>
                  )}
                />

                {/* Priority 17: Last Contacted By */}
                <FormField
                  control={form.control}
                  name="lastContactedBy"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Last Contacted By</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="Enter name (max 50 characters)"
                          maxLength={50}
                          {...field}
                          onChange={(e) => {
                            field.onChange(e);
                            setLastContactedByCount(e.target.value.length);
                          }}
                          data-testid="input-last-contacted-by"
                        />
                      </FormControl>
                      <p className="text-xs text-gray-500 mt-0.5" data-testid="text-last-contacted-by-count">
                        {lastContactedByCount}/50 characters
                      </p>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 18: Date of Birth */}
                <FormField
                  control={form.control}
                  name="dateOfBirth"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Date of Birth</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <Input 
                            type="date" 
                            {...field} 
                            value={field.value || ""}
                            onChange={(e) => field.onChange(e.target.value || null)}
                            data-testid="input-dob" 
                          />
                          {field.value && (
                            <button
                              type="button"
                              onClick={() => field.onChange(null)}
                              className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                              title="Clear date"
                            >
                              <X className="h-4 w-4" />
                            </button>
                          )}
                        </div>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 19: Customer Category */}
                <FormField
                  control={form.control}
                  name="customerCategory"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">
                        Customer Category <span className="text-red-500">*</span>
                      </FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-customer-category">
                            <SelectValue placeholder="Select category" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {Object.values(CustomerCategory).map((category) => (
                            <SelectItem key={category} value={category}>
                              {formatCustomerCategoryLabel(category)}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Priority 20: Lead Created By */}
                <FormField
                  control={form.control}
                  name="leadCreatedBy"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs">Lead Created By</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="Enter creator name (max 50 characters)"
                          maxLength={50}
                          {...field}
                          onChange={(e) => {
                            field.onChange(e);
                            setLeadCreatedByCount(e.target.value.length);
                          }}
                          data-testid="input-lead-created-by"
                        />
                      </FormControl>
                      <p className="text-xs text-gray-500 mt-0.5" data-testid="text-lead-created-by-count">
                        {leadCreatedByCount}/50 characters
                      </p>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Custom Lead Source Fields */}
                {form.watch("leadSource") === LeadSource.OTHER && (
                  <FormField
                    control={form.control}
                    name="customLeadSource"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Custom Lead Source</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="Enter custom lead source (max 50 characters)"
                            maxLength={50}
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setCustomSourceCount(e.target.value.length);
                            }}
                            data-testid="input-custom-lead-source"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-source-count">
                          {customSourceCount}/50 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )}

                {form.watch("leadSource") === LeadSource.REFERRAL && (
                  <FormField
                    control={form.control}
                    name="customReferralSource"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Referral Source</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="Enter referral source (max 50 characters)"
                            maxLength={50}
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setCustomReferralCount(e.target.value.length);
                            }}
                            data-testid="input-custom-referral-source"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-referral-count">
                          {customReferralCount}/50 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )}

                {form.watch("leadSource") === LeadSource.GENERATED_BY && (
                  <FormField
                    control={form.control}
                    name="customGeneratedBy"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Generated By</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="Enter generated by (max 50 characters)"
                            maxLength={50}
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setCustomGeneratedByCount(e.target.value.length);
                            }}
                            data-testid="input-custom-generated-by"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-generated-by-count">
                          {customGeneratedByCount}/50 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )}

                {form.watch("preferredCommunicationChannel") === "other" && (
                  <FormField
                    control={form.control}
                    name="customCommunicationChannel"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Custom Communication Channel</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="Enter custom channel (max 50 characters)"
                            maxLength={50}
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setCustomCommChannelCount(e.target.value.length);
                            }}
                            data-testid="input-custom-communication-channel"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-comm-channel-count">
                          {customCommChannelCount}/50 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )}
              </div>
            </>
          ) : (
            <>
              {/* Original Add Lead Form Layout */}
              {/* Personal Information Section */}
              <div>
                <div className="flex items-center space-x-2 mb-2">
                  <User className="h-4 w-4 text-primary" />
                  <h4 className="text-sm font-semibold text-gray-900">Personal Information</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                  <FormField
                    control={form.control}
                    name="name"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">
                          Full Name <span className="text-red-500">*</span>
                        </FormLabel>
                        <FormControl>
                          <Input placeholder="Enter full name" {...field} data-testid="input-name" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="phoneNumber"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">
                          Phone Number <span className="text-red-500">*</span>
                        </FormLabel>
                        <FormControl>
                          <Input placeholder="Enter phone number" {...field} data-testid="input-phone" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="email"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Email Address</FormLabel>
                        <FormControl>
                          <Input type="email" placeholder="john@example.com" {...field} data-testid="input-email" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="dateOfBirth"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Date of Birth</FormLabel>
                        <FormControl>
                          <div className="relative">
                            <Input 
                              type="date" 
                              {...field} 
                              value={field.value || ""}
                              onChange={(e) => field.onChange(e.target.value || null)}
                              data-testid="input-dob" 
                            />
                            {field.value && (
                              <button
                                type="button"
                                onClick={() => field.onChange(null)}
                                className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                                title="Clear date"
                              >
                                <X className="h-4 w-4" />
                              </button>
                            )}
                          </div>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="customerCategory"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">
                          Customer Category <span className="text-red-500">*</span>
                        </FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-customer-category">
                              <SelectValue placeholder="Select category" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {Object.values(CustomerCategory).map((category) => (
                              <SelectItem key={category} value={category}>
                                {formatCustomerCategoryLabel(category)}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="leadStatus"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">
                          Lead Status <span className="text-red-500">*</span>
                        </FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-lead-status">
                              <SelectValue placeholder="Select status" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {Object.values(LeadStatus).map((status) => (
                              <SelectItem key={status} value={status}>
                                {formatLeadStatusLabel(status)}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="leadSource"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">
                          Lead Source <span className="text-red-500">*</span>
                        </FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-lead-source">
                              <SelectValue placeholder="Select lead source" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {Object.values(LeadSource).map((source) => (
                              <SelectItem key={source} value={source}>
                                {formatLeadSourceLabel(source)}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="leadCreatedBy"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Lead Created By</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="Enter creator name (max 50 characters)"
                            maxLength={50}
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setLeadCreatedByCount(e.target.value.length);
                            }}
                            data-testid="input-lead-created-by"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-lead-created-by-count">
                          {leadCreatedByCount}/50 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </div>

              <Separator className="my-2" />

              {/* Communication & Follow-up Section */}
              <div>
                <div className="flex items-center space-x-2 mb-2">
                  <MessageSquare className="h-4 w-4 text-primary" />
                  <h4 className="text-sm font-semibold text-gray-900">Communication & Follow-up</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                  <FormField
                    control={form.control}
                    name="nextFollowupDate"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Next Followup Date</FormLabel>
                        <FormControl>
                          <div className="relative">
                            <Input
                              type="date"
                              {...field}
                              value={field.value || ""}
                              onChange={(e) => {
                                const value = e.target.value;
                                field.onChange(value || null);
                                if (isEditing && value) {
                                  const today = new Date();
                                  const isoToday = new Date(today.getTime() - today.getTimezoneOffset() * 60000)
                                    .toISOString()
                                    .split("T")[0];
                                  form.setValue("lastContactedDate", isoToday, { shouldDirty: true });
                                }
                              }}
                              data-testid="input-next-followup-date"
                            />
                            {field.value && (
                              <button
                                type="button"
                                onClick={() => field.onChange(null)}
                                className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                                title="Clear date"
                              >
                                <X className="h-4 w-4" />
                              </button>
                            )}
                          </div>
                        </FormControl>
                        <FormMessage />
                        <p className="text-xs text-gray-500">Must be today or in the future</p>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="lastContactedDate"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Last Contacted Date</FormLabel>
                        <FormControl>
                          <div className="relative">
                            <Input 
                              type="date" 
                              {...field} 
                              value={field.value || ""}
                              onChange={(e) => field.onChange(e.target.value || null)}
                              data-testid="input-last-contacted-date" 
                            />
                            {field.value && (
                              <button
                                type="button"
                                onClick={() => field.onChange(null)}
                                className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                                title="Clear date"
                              >
                                <X className="h-4 w-4" />
                              </button>
                            )}
                          </div>
                        </FormControl>
                        <FormMessage />
                        <p className="text-xs text-gray-500">Cannot be in the future</p>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="lastContactedBy"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Last Contacted By</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="Enter name (max 50 characters)"
                            maxLength={50}
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setLastContactedByCount(e.target.value.length);
                            }}
                            data-testid="input-last-contacted-by"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-last-contacted-by-count">
                          {lastContactedByCount}/50 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="preferredCommunicationChannel"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Preferred Communication Channel</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-communication-channel">
                              <SelectValue placeholder="Select channel" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="email">Email</SelectItem>
                            <SelectItem value="phone">Phone</SelectItem>
                            <SelectItem value="whatsapp">WhatsApp</SelectItem>
                            <SelectItem value="sms">SMS</SelectItem>
                            <SelectItem value="in-person">In Person</SelectItem>
                            <SelectItem value="linkedin">LinkedIn</SelectItem>
                            <SelectItem value="other">Other</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* Custom Lead Source Fields */}
                  {form.watch("leadSource") === LeadSource.OTHER && (
                    <FormField
                      control={form.control}
                      name="customLeadSource"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-xs">Custom Lead Source</FormLabel>
                          <FormControl>
                            <Input
                              placeholder="Enter custom lead source (max 50 characters)"
                              maxLength={50}
                              {...field}
                              onChange={(e) => {
                                field.onChange(e);
                                setCustomSourceCount(e.target.value.length);
                              }}
                              data-testid="input-custom-lead-source"
                            />
                          </FormControl>
                          <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-source-count">
                            {customSourceCount}/50 characters
                          </p>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  )}

                  {form.watch("leadSource") === LeadSource.REFERRAL && (
                    <FormField
                      control={form.control}
                      name="customReferralSource"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-xs">Referral Source</FormLabel>
                          <FormControl>
                            <Input
                              placeholder="Enter referral source (max 50 characters)"
                              maxLength={50}
                              {...field}
                              onChange={(e) => {
                                field.onChange(e);
                                setCustomReferralCount(e.target.value.length);
                              }}
                              data-testid="input-custom-referral-source"
                            />
                          </FormControl>
                          <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-referral-count">
                            {customReferralCount}/50 characters
                          </p>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  )}

                  {form.watch("leadSource") === LeadSource.GENERATED_BY && (
                    <FormField
                      control={form.control}
                      name="customGeneratedBy"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-xs">Generated By</FormLabel>
                          <FormControl>
                            <Input
                              placeholder="Enter generated by (max 50 characters)"
                              maxLength={50}
                              {...field}
                              onChange={(e) => {
                                field.onChange(e);
                                setCustomGeneratedByCount(e.target.value.length);
                              }}
                              data-testid="input-custom-generated-by"
                            />
                          </FormControl>
                          <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-generated-by-count">
                            {customGeneratedByCount}/50 characters
                          </p>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  )}

                  {form.watch("preferredCommunicationChannel") === "other" && (
                    <FormField
                      control={form.control}
                      name="customCommunicationChannel"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-xs">Custom Communication Channel</FormLabel>
                          <FormControl>
                            <Input
                              placeholder="Enter custom channel (max 50 characters)"
                              maxLength={50}
                              {...field}
                              onChange={(e) => {
                                field.onChange(e);
                                setCustomCommChannelCount(e.target.value.length);
                              }}
                              data-testid="input-custom-communication-channel"
                            />
                          </FormControl>
                          <p className="text-xs text-gray-500 mt-0.5" data-testid="text-custom-comm-channel-count">
                            {customCommChannelCount}/50 characters
                          </p>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  )}

                  <FormField
                    control={form.control}
                    name="additionalNotes"
                    render={({ field }) => (
                      <FormItem className="md:col-span-3">
                        <FormLabel className="text-xs">Additional Notes</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="Add any additional notes (max 200 characters)"
                            maxLength={200}
                            rows={1}
                            className="min-h-[32px] resize-none"
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setNotesCount(e.target.value.length);
                            }}
                            data-testid="textarea-additional-notes"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-notes-count">
                          {notesCount}/200 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </div>

              <Separator className="my-2" />

              {/* Company Information Section */}
              <div>
                <div className="flex items-center space-x-2 mb-2">
                  <Building className="h-4 w-4 text-primary" />
                  <h4 className="text-sm font-semibold text-gray-900">Company Information</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  <FormField
                    control={form.control}
                    name="companyName"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Company Name</FormLabel>
                        <FormControl>
                          <Input placeholder="Enter company name" {...field} data-testid="input-company" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="designation"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Designation</FormLabel>
                        <FormControl>
                          <Input placeholder="Enter designation" {...field} data-testid="input-designation" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="customerInterestedIn"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Customer Interested in</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="Describe customer interests (max 100 characters)"
                            maxLength={100}
                            {...field}
                            onChange={(e) => {
                              field.onChange(e);
                              setInterestedInCount(e.target.value.length);
                            }}
                            data-testid="input-customer-interested-in"
                          />
                        </FormControl>
                        <p className="text-xs text-gray-500 mt-0.5" data-testid="text-interested-in-count">
                          {interestedInCount}/100 characters
                        </p>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </div>

              <Separator className="my-2" />

              {/* Address Information Section */}
              <div>
                <div className="flex items-center space-x-2 mb-2">
                  <MapPin className="h-4 w-4 text-primary" />
                  <h4 className="text-sm font-semibold text-gray-900">Address Information</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                  <FormField
                    control={form.control}
                    name="city"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">City</FormLabel>
                        <FormControl>
                          <Input placeholder="Enter city" {...field} data-testid="input-city" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="state"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">State</FormLabel>
                        <FormControl>
                          <Input placeholder="Enter state" {...field} data-testid="input-state" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="country"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Country</FormLabel>
                        <FormControl>
                          <Input placeholder="Enter country" {...field} data-testid="input-country" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="pincode"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs">Pincode/Zipcode</FormLabel>
                        <FormControl>
                          <Input placeholder="123456" {...field} data-testid="input-pincode" />
                        </FormControl>
                        <FormMessage />
                        <p className="text-xs text-gray-500">6 digits for Indian pincodes</p>
                      </FormItem>
                    )}
                  />
                </div>
              </div>
            </>
          )}
        </form>
      </Form>
    </>
  );
}
